### ISSUE TITLE
Biplots

### ISSUE THREAD

**Issue by mstaniak** [mstaniak/varclust_example#1]
@sjwilczynski umiesz powiedzieć, dlaczego faktory zwracane przez mlcc.bic nie są tym samym, co wywołanie prcomp na macierzy zmiennych z jednego klastra? Przesledzilem kod Piotrka, ale nie widze, o co chodzi.

**Comment by sjwilczynski** [comment]
Strzał jest taki, ale pewności nie mam. W ostatniej iteracji algorytmu
liczymy składowe w każdej grupie a potem na nowo przydzielamy zmienne do
grup. Więc składowe zwracane przez algorytm to skladowe z poprzedniej
iteracji. Tak, to niefajne, jak bedę miał chwilę to poprawię

**Comment by mstaniak** [comment]
Jak wrócę do domu, zrobię szybki eksperyment, żeby sprawdzić

**Comment by sjwilczynski** [comment]
Problemy:
- przy startowaniu algorytmu z podziału wynikającego z zastosowania SSC,
zwracana wartość BIC to -Inf,
- w pracy licencjackiej jest mowa, że podział jest wybierany na podstawie
mBIC, w pakiecie kryterium nazywa się BIC,
- o ile rozumiem,faktory to składowe główne obliczone dla klastra, ale nie
udało mi się uzyskać takiego samego wyniku w prcomp() i odczytania
faktorów mlcc.bic. Jak zrozumiem tę kwestię, może fajnie będzie
dodać biplot dla takiego PCA w ustalonym klastrze,
- losowy start algorytmu sprawia, że różne liczby klastrów w różnych
"odpaleniach" algorytmu potrafią zmieniać interpretację ostatecznego
podziału. To spory problem,
- nie wiem, na ile warto pokazywać jakieś wydruki z R-a, więc na razie nic
nie dodawałem.

Co do tych problemów:
1. Na razie nie wiem, dziwne
2. Kosmetyka, ale dzięki za uwagę - a w którym konkretnie miejscu miałeś
dokumentacje na myśli?
3. To już pisałem
4. Cecha każdego algorytmu opartego na kmeans (próbowaliśmy jakiś
deterministycznych inicjalizacji, nie działało tak dobrze jak losowo) -
można ten efekt zredukować zwiększając numb.runs i zmieniając greedy na
FALSE (w mlcc.bic)

**Comment by mstaniak** [comment]
2. Hmm. Licencjat:
> Choose the model with the highest value of mBIC and return the model (segmentation,
mBIC, factors) as the result.
Pakiet:
- funkcja nazywa się mlcc.bic
- jej wynik ma pole "BIC"
Dla mnie to niejasne (;
4. Wiem, ale to utrudnia mocno napisanie sensownej interpretacji (;

**Comment by sjwilczynski** [comment]
Co do stabilności - można zmenić parametry max.iter (on jest zarówno w mlcc.bic jak i mlcc.reps) i greedy( który jest tylko w mlcc.bic). Co do -Inf na klastrowaniu przy inicjalizacji z SSC, źle użyłeś parametr initial.segmentations. Jak sama nazwa wskazuje możesz podać więcej niż jedną, wieć powinna to być lista segmentacji, a nie jedna segmentacja (oczywiście error by się przydał, ale dziwię się, że nie popatrzyłeś, że w segmentacji wychodzi jedna zmienna). A propo tego, że po zwiększeniu max.iter wychodziły ci 2 klastry - to dlatego, że dla mlcc.reps domyślną wartością dla number.clusters jest 2. Tylko mlcc.bic testuje różne liczby klastrów. Na varcluscie jest branch tests_and_remarks tam już pca liczy się także po iteracjach kmeansów, jak chcesz możesz się z updatować. Poprawiłem też jeden błąd w peselu (kiedyś ci mówiłem, że jakby coś nie działało to zrevertuj pakiet do jakiejś wersji, pamiętasz? Okazało się ze problem był w peselu a varclust działał i działa prawidłowo) - możesz albo poczekać aż Sobczyk zmerguje mojego pull requesta do pesela albo pobrać pesela ode mnie (mam forka). A jutro to chętnie przez 5 min bym się dowiedział co się dzieje w tym pliku varclust_usage.R

**Comment by mstaniak** [comment]
1. Super, dzięki. Sprawdzałem, czy tam trzeba podać listę i jakimś cudem nie zauważyłem "list of..." w dokumentacji.  Error byłby okej, ale dokumentacja wyjaśnia, co powinno być. Moje przeoczenie.
2. To literówka, miało być mlcc.bic. Dobrze, że ją wypatrzyłeś.
Dzięki za wszystkie informacje. Jutro mogę być dopiero po wykładzie, bo muszę coś załatwić z rana, ale będe.

**Comment by sjwilczynski** [comment]
Jak masz przychodzić tylko po to to nie ma potrzeby ;)

**Comment by mstaniak** [comment]
I tak muszę być od 10, więc nie ma problemu

**Comment by mstaniak** [comment]
Nie dotarłem, porozmawiamy na labie

**Comment by sjwilczynski** [comment]
Jak tam, będzie coś na wt?

**Comment by mstaniak** [comment]
Będzie, spotkajmy się

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
Dnia 11 marca 2018 12:49 PM, Stanisław <notifications@github.com> napisał:

**Comment by sjwilczynski** [comment]
Ok, to o 16:15 u Bogdan (bo muszę coś załatwić po wykładzie z ASP)
