### ISSUE TITLE
Plik sensor_locations.csv

### ISSUE THREAD

**Issue by sjwilczynski** [mstaniak/varclust_example#3]
![image](https://user-images.githubusercontent.com/19153565/44619904-677e0500-a88c-11e8-9fef-73c7f097aba8.png)

Hej, próbowałem u siebie odpalić varclust_usage i dostaję błąd ze screena. Jakieś hinty? W ogóle gdzie jest plik sensor_locations.csv bo coś w repo go za bardzo nie widzę, a się z niego czyta.

**Comment by mstaniak** [comment]
już ok?

**Comment by sjwilczynski** [comment]
Tak dzięki, udało mi się nawet tą mapkę w końcu zrobić
